### ISSUE TITLE
display: unexpected semicolon, expecting comma or }

### ISSUE THREAD

**Issue by mewmew** [richardwilkes/ui#2]
Hi!

I tried to go-get this project, and got the following error:

**Edit:** this was on rev 56badff9dd1403d4ed77e4b091cf8d3304246216.

```
$ go get -v -u github.com/richardwilkes/ui/...
# github.com/richardwilkes/ui/display
goget/src/github.com/richardwilkes/ui/display/display_linux.go:10:10: syntax error: unexpected semicolon, expecting comma or }
```

**Comment by richardwilkes** [comment]
Fixed in 
https://github.com/richardwilkes/ui/commit/cb5c8d61d5882cbd3bba30d2b86fc775ce5f77c5 -- as mentioned in the other bug report, I haven't spent much time on the Linux side (nor the macOS side, either, but certainly more there).
