### ISSUE TITLE
draw: could not determine kind of name for C.cairo_xlib_surface_set_size

### ISSUE THREAD

**Issue by mewmew** [richardwilkes/ui#3]
When trying to go-get this project, I got the following error:

**Edit:** this was on rev 56badff9dd1403d4ed77e4b091cf8d3304246216.

```
# github.com/richardwilkes/ui/draw
goget/src/github.com/richardwilkes/ui/draw/surface_linux.go:19:3: could not determine kind of name for C.cairo_xlib_surface_set_size
```

What version of Cairo is supported?

I'm running 1.16.0 on Arch Linux.

```
u@x1 ~> pacman -Q cairo
cairo 1.16.0-1
```

**Comment by richardwilkes** [comment]
Cairo 1.14.12 was what it was created with. Note: I have not spent much time with the Linux side of things lately, so not sure how much bit-rot has occurred.

**Comment by mewmew** [comment]
> Cairo 1.14.12 was what it was created with. Note: I have not spent much time with the Linux side of things lately, so not sure how much bit-rot has occurred.

Ok, good to know. Thanks.
